### ISSUE TITLE
Broadcast notifications from server

### ISSUE THREAD

**Issue by skaldarnar** [Terasology/Notifications#5]
Currently the notification system is a pure client-system, and the two use cases are client-side-only notifications. These notifications work just fine (in both single and multi player), but we don't have any example or proof of concept (PoC).

**Task:** Find a use case for a _server broadcast notification_ to all players and implement that (maybe the  https://github.com/Terasology/ServerMOTD module could make use of this?). 

- [ ] implement a sample for a _server broadcast notification_ (in some other module)
- [ ] test that everything is working (single player, hosting a game, headless server + clients)
- [ ] document how a _broadcast event_ usually looks like
- [ ] (Optional) consider adding a new server-side system to automatically send _broadcast events_ from a single notification

Requires understanding (or willingness to investigate) how events can be send from server to client and whether any changes are required for this to work properly.
